services:
  delta:
    build:
      context: .
    env_file: ".env"
    container_name: delta
    environment:
      NODE_ENV: production
    networks:
      - prom
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongodb/mongodb-community-server:7.0.9-ubi8
    container_name: delta-mongo
    # for debugging
    ports:
      - 100.80.20.80:27888:27017
    volumes:
      - data:/data/db
      - config:/data/configdb
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/delta --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  data:
    driver: local
  config:
    driver: local

networks:
  prom:
    external: true
